version: '3'
services:
    app:
      container_name: server
      build: .
      command: npm start
      ports:
        - '3060:3060'
      links:
        - database
      volumes:
        - .:/usr/app
      depends_on:
        - database
      networks:
        - app-network

    database:
      container_name: database
      image: mysql:5.7
      ports:
        - '3308:3306'
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: xF#2940z
        MYSQL_DATABASE: project_database
        MYSQL_USER: masteruser
        MYSQL_PASSWORD: mtulhm898#
      networks:
        - app-network

    phpmyadmin:
      container_name: pma
      image: phpmyadmin/phpmyadmin:latest
      depends_on:
        - database
      environment:
        PMA_HOST: database
        MYSQL_ROOT_PASSWORD: xF#2940z
      ports:
        - "8090:80"
      restart: always
      networks:
        - app-network
  
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
